// backend/models/Notification.js — Batch 12 (guide feedback #5)
//
// In-app notifications. The first use case is membership-expiry alerts
// generated by the daily cron at 15/7/1 days before a subscription's
// endDate, but the schema is generic enough to hold other kinds later
// (payment received, new enquiry, task assigned, etc.).
//
// Audience: every notification is addressed to either the gym admin
// (audience='admin', read by anyone with admin/staff role for that
// company) or a specific customer (audience='customer', customerId is
// required and only that customer can read it).

const mongoose = require('mongoose')

const NOTIFICATION_KINDS = [
    'membership_expiry',
    // Future: 'payment_received', 'new_enquiry', 'task_assigned', etc.
]

const notificationSchema = new mongoose.Schema({
    audience: {
        type: String,
        enum: ['admin', 'customer'],
        required: true,
        index: true,
    },

    // Required when audience === 'customer'. Refers to a Customer document
    // (NOT a User document — see paymentController for the user → customer
    // lookup pattern).
    customerId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Customer',
        default: null,
        index: true,
    },

    kind: { type: String, enum: NOTIFICATION_KINDS, required: true },

    title:   { type: String, trim: true, required: true },   // e.g. "Membership expiring in 7 days"
    message: { type: String, trim: true, required: true },   // longer body shown in the dropdown

    // Subscription this notification is about (optional but populated for
    // membership_expiry kind). Lets the UI deep-link to the subscription.
    subscriptionId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Subscription',
        default: null,
    },

    // 15 / 7 / 1 for membership_expiry; null for other kinds.
    daysOut: { type: Number, default: null },

    read: { type: Boolean, default: false, index: true },

    // Multi-tenancy
    companyId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Company',
        required: true,
        index: true,
    },
}, { timestamps: true })

// Compound index for the most common query: "give me unread notifications
// for this admin/customer in this company, newest first".
notificationSchema.index({ companyId: 1, audience: 1, customerId: 1, read: 1, createdAt: -1 })

// De-dupe guard: prevent the cron from creating two notifications for the
// same subscription at the same daysOut tier (which could happen if the
// cron ran twice on the same day, or if `remindersSent` got cleared).
// Partial filter so it only applies to membership_expiry kind.
notificationSchema.index(
    { subscriptionId: 1, audience: 1, customerId: 1, daysOut: 1, kind: 1 },
    {
        unique: true,
        partialFilterExpression: { kind: 'membership_expiry' },
    },
)

module.exports = mongoose.model('Notification', notificationSchema)
